SECRET_KEY = '1234'
SQLALCHEMY_DATABASE_URI = "sqlite:///../db_directory/library.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False

SECURITY_TOKEN_AUTHENTICATION_HEADER = 'Authentication-Token'

WTF_CSRF_ENABLED = False
JWT_SECRET_KEY = 'JWT_SECRET_KEY'



# CACHE_TYPE = "RedisCache"
# CACHE_REDIS_URL = "redis://localhost:6379/0"
# DEBUG = False
